/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexcopyRouteImport } from './routes/index copy'
import { Route as BookSlugcopyRouteImport } from './routes/book.$slug copy'
import { Route as CabinsSlugRouteImport } from './routes/cabins.$slug'
import { Route as ReceiptReferenceRouteImport } from './routes/receipt.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexcopyRoute = IndexcopyRouteImport.update({
  id: '/index copy',
  path: '/index copy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugcopyRoute = BookSlugcopyRouteImport.update({
  id: '/$slug copy',
  path: '/$slug copy',
  getParentRoute: () => BookRoute,
} as any)
const CabinsSlugRoute = CabinsSlugRouteImport.update({
  id: '/cabins/$slug',
  path: '/cabins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptReferenceRoute = ReceiptReferenceRouteImport.update({
  id: '/receipt/$reference',
  path: '/receipt/$reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRouteWithChildren
  '/index copy': typeof IndexcopyRoute
  '/book/$slug copy': typeof BookSlugcopyRoute
  '/cabins/$slug': typeof CabinsSlugRoute
  '/receipt/$reference': typeof ReceiptReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRouteWithChildren
  '/index copy': typeof IndexcopyRoute
  '/book/$slug copy': typeof BookSlugcopyRoute
  '/cabins/$slug': typeof CabinsSlugRoute
  '/receipt/$reference': typeof ReceiptReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRouteWithChildren
  '/index copy': typeof IndexcopyRoute
  '/book/$slug copy': typeof BookSlugcopyRoute
  '/cabins/$slug': typeof CabinsSlugRoute
  '/receipt/$reference': typeof ReceiptReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/index copy'
    | '/book/$slug copy'
    | '/cabins/$slug'
    | '/receipt/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book'
    | '/index copy'
    | '/book/$slug copy'
    | '/cabins/$slug'
    | '/receipt/$reference'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/index copy'
    | '/book/$slug copy'
    | '/cabins/$slug'
    | '/receipt/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRouteWithChildren
  IndexcopyRoute: typeof IndexcopyRoute
  CabinsSlugRoute: typeof CabinsSlugRoute
  ReceiptReferenceRoute: typeof ReceiptReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index copy': {
      id: '/index copy'
      path: '/index copy'
      fullPath: '/index copy'
      preLoaderRoute: typeof IndexcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug copy': {
      id: '/book/$slug copy'
      path: '/$slug copy'
      fullPath: '/book/$slug copy'
      preLoaderRoute: typeof BookSlugcopyRouteImport
      parentRoute: typeof BookRoute
    }
    '/cabins/$slug': {
      id: '/cabins/$slug'
      path: '/cabins/$slug'
      fullPath: '/cabins/$slug'
      preLoaderRoute: typeof CabinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$reference': {
      id: '/receipt/$reference'
      path: '/receipt/$reference'
      fullPath: '/receipt/$reference'
      preLoaderRoute: typeof ReceiptReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookSlugcopyRoute: typeof BookSlugcopyRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookSlugcopyRoute: BookSlugcopyRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRouteWithChildren,
  IndexcopyRoute: IndexcopyRoute,
  CabinsSlugRoute: CabinsSlugRoute,
  ReceiptReferenceRoute: ReceiptReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
